import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout } from '../src/components/layout/Layout'
import { Main } from '../src/components/main/Main'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>360 Polls</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Main />
      </Layout>
    </>
  )
}

export default Home
